# Assignment 2 - COMP90024 Course at The University of Melbourne
#
# Cluster and Cloud Computing - Team 48
#
# Authors:
#
#  * Arnav Garg (Student ID: 1248298)
#  * Piyush Bhandula (Student ID: 1163716)
#  * Jay Dave (Student ID: 1175625)
#  * Vishnu Priya G (Student ID: 1230719)
#  * Gurkirat Singh Chohan (Student ID: 1226595)
#
# Location: India, Melbourne, Singapore
#
- name: Create git directory
  tags: 'git-repo dir'
  become: yes
  file:
    path: "{{ git_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory

- name: clone a repository
  become: yes
  git:
    repo: 'https://github.com/arnavgarg123/COMP90024-ClusterAndCloudComputing-Assignment2.git'
    dest: "{{ git_dir }}"
    update: yes

- name: Create ip file
  tags: always
  become: yes
  file:
    path: "{{ ip_path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: touch

- name: Add ip to instances
  become: yes
  lineinfile:
    path: '{{ ip_path }}'
    #regexp: '.*{{ item }}$'
    line: "{{ item }}"
    state: present
  #when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.db_harvestor }}"

- name: Create ip file
  tags: always
  become: yes
  file:
    path: "{{ ip_path2 }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: touch

- name: Add ip to instances
  become: yes
  lineinfile:
    path: '{{ ip_path2 }}'
    #regexp: '.*{{ item }}$'
    line: "{{ item }}"
    state: present
  #when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.db_harvestor }}"