- name: Create couchdb directory
  tags: 'couchdb'
  become: yes
  file:
    path: "{{ couch_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory

- name: Create Compose in cloud
  tags: 'couchdb'
  become: yes
  template:
    src: ../../../../CouchDB-Cluster
    dest: '{{ couch_dir }}/docker-compose.yaml'
    owner: '{{ ansible_user }}'
    group: "{{ ansible_user }}"

- name: Run docker compose
  tags: 'couchdb'
  become: yes
  docker_compose:
    project_src: "{{ couch_dir }}"
    pull: yes
    state: present
    remove_orphans: yes
    recreate: always
