# Assignment 2 - COMP90024 Course at The University of Melbourne
#
# Cluster and Cloud Computing - Team 48
#
# Authors:
#
#  * Arnav Garg (Student ID: 1248298)
#  * Piyush Bhandula (Student ID: 1163716)
#  * Jay Dave (Student ID: 1175625)
#  * Vishnu Priya G (Student ID: 1230719)
#  * Gurkirat Singh Chohan (Student ID: 1226595)
#
# Location: India, Melbourne, Singapore
#

# Stop webapp container
- name: Stop webapp Docker container
  become: yes
  docker_container:
    name: flask_app
    state: absent

# Stop nginx container
- name: Stop nginx Docker container
  become: yes
  docker_container:
    name: nginx
    state: absent

# Start nginx and webapp
- name: Run docker compose
  tags: 'webapp'
  become: yes
  docker_compose:
    remove_images: local
    project_src: "{{ web_dir }}"
    build: yes
    nocache: yes
    pull: yes
    state: present
    remove_orphans: yes
    recreate: always