# Assignment 2 - COMP90024 Course at The University of Melbourne
#
# Cluster and Cloud Computing - Team 48
#
# Authors:
#
#  * Arnav Garg (Student ID: 1248298)
#  * Piyush Bhandula (Student ID: 1163716)
#  * Jay Dave (Student ID: 1175625)
#  * Vishnu Priya G (Student ID: 1230719)
#  * Gurkirat Singh Chohan (Student ID: 1226595)
#
# Location: India, Melbourne, Singapore
#
- hosts: localhost
  vars:
    ansible_python_interpreter: /home/arnav/anaconda3/bin/python3
  vars_files:
    - variable/var.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance

- hosts: db_harvestor
  vars_files:
    - variable/couchdb_var.yaml
  gather_facts: true

  roles:
    - role: common
    - role: couch-volumes
    - role: docker
    - role: git-clone
    - role: docker-compose
    
- hosts: db_harvestor:!master
  vars_files:
    - variable/couchdb_var.yaml
  gather_facts: true

  roles:
    - role: couch-cluster

- hosts: web
  gather_facts: true

  roles:
    - role: common
    - role: docker
    - role: git-clone
    - role: web-app-docker-compose
