- hosts: localhost
  vars:
    ansible_python_interpreter: /home/arnav/anaconda3/bin/python3
  vars_files:
    - variable/var.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance
