# Assignment 2 - COMP90024 Course at The University of Melbourne
#
# Cluster and Cloud Computing - Team 48
#
# Authors:
#
#  * Arnav Garg (Student ID: 1248298)
#  * Piyush Bhandula (Student ID: 1163716)
#  * Jay Dave (Student ID: 1175625)
#  * Vishnu Priya G (Student ID: 1230719)
#  * Gurkirat Singh Chohan (Student ID: 1226595)
#
# Location: India, Melbourne, Singapore
#

# Create volumes
- name: Create volume on MRC
  os_volume:
    display_name: "{{ item.vol_name }}"
    size: "{{ item.vol_size }}"
    availability_zone: "{{ availability_zone }}"
    wait: yes
    timeout: 600
    state: present
  loop: '{{ volumes }}'
  register: os_volume

# Get a list of volume Ids from the return value of os_volume
- name: Create a list of volume Ids
  set_fact:
    volume_ids: '{{ volume_ids|default([]) + [ item.id ] }}'
  loop: '{{ os_volume.results }}'

- debug:
    msg: "Volume {{ volume_ids }} has been created."
