# Assignment 2 - COMP90024 Course at The University of Melbourne
#
# Cluster and Cloud Computing - Team 48
#
# Authors:
#
#  * Arnav Garg (Student ID: 1248298)
#  * Piyush Bhandula (Student ID: 1163716)
#  * Jay Dave (Student ID: 1175625)
#  * Vishnu Priya G (Student ID: 1230719)
#  * Gurkirat Singh Chohan (Student ID: 1226595)
#
# Location: India, Melbourne, Singapore
#

# Pushing twitter api keys to cloud
- name: Create twiter api key file in cloud
  tags: 'twiter_api_key_file'
  become: yes
  template:
    src: ./tweetapi.json.j2
    dest: '{{ api_path }}'
    owner: '{{ ansible_user }}'
    group: "{{ ansible_user }}"