# Assignment 2 - COMP90024 Course at The University of Melbourne
#
# Cluster and Cloud Computing - Team 48
#
# Authors:
#
#  * Arnav Garg (Student ID: 1248298)
#  * Piyush Bhandula (Student ID: 1163716)
#  * Jay Dave (Student ID: 1175625)
#  * Vishnu Priya G (Student ID: 1230719)
#  * Gurkirat Singh Chohan 1226595
#
# Location: India, Melbourne, Singapore
#

#availability zone
availability_zone: melbourne-qh2-uom

#volume
volumes:
  - vol_name: vol-11
    vol_size: 100
  - vol_name: vol-22
    vol_size: 100
  - vol_name: vol-33
    vol_size: 100
  - vol_name: vol-44
    vol_size: 10

#security group
security_groups:
  - name: ssh_access
    description: "ssh access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb_access
    description: "couchdb access"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: http_access
    description: "HTTP access"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

#instance
harvest_instances:
  - name: db-harvest-1
    volumes: ["vol-11"]
  - name: db-harvest-2
    volumes: ["vol-22"]
  - name: db-harvest-3
    volumes: ["vol-33"]
web_instance:
  - name: db-web-1
    volumes: ["vol-44"]

instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: Test
harvest_instance_flavor: uom.mse.2c9g
web_instance_flavor: uom.mse.1c4g