#availability zone
availability_zone: melbourne-qh2-uom

#volume
volumes:
  - vol_name: vol-1
    vol_size: 10
  - vol_name: vol-2
    vol_size: 10

#security group
security_groups:
  - name: ssh_access
    description: "ssh access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http_access
    description: "HTTP access"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

#instance
instances:
  - name: instance1
    volumes: ["vol-1"]
  - name: instance2
    volumes: ["vol-2"]

instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: Test
instance_flavor: uom.mse.2c9g
